title = "Zammad gitleaks Configuration"

[extend]
useDefault = true

[allowlist]
description = "global allow list"
paths = [
  '''^doc/developer_manual/cookbook/how-to-setup-smime-integration.md''',
  '''^log/''',
  '''^spec/fixtures/files/smime/.*\.key''',
  '''^test/data/saml/zammad-client.json''',
  '''^test/data/telegram/private/sticker.json''',
  '''^test/data/vcr_cassettes/''',
  '''^tmp/''',
]
regexTarget = "line"
regexes = []
