before_script:
  - bundle install

stages:
  - pre
  - test
  - browser

rubocop:
  stage: pre
  script:
    - bundle exec rubocop

job_unit:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh test ci_zammad_unit
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - rake db:seed
    - rake test:units
    - rake test:controllers

job_integration_email_helper:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh test ci_zammad_email_helper
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/email_helper_test.rb

job_integration_geo_ip:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh test ci_zammad_geo_ip
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/geo_ip_test.rb

job_integration_geo_location:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh test ci_zammad_geo_location
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/geo_location_test.rb

job_integration_geo_calendar:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh test ci_zammad_geo_calendar
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/geo_calendar_test.rb

job_integration_user_agent:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh test ci_zammad_user_agent
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/user_agent_test.rb

job_integration_es:
  stage: test
  script:
    - export RAILS_ENV=test
    - script/build/test_db_config.sh test ci_zammad_es
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/elasticsearch_test.rb
    - ruby -I test/ test/controllers/search_controller_test.rb
    - ruby -I test/ test/integration/report_test.rb

job_integration_otrs_5:
  stage: test
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz599.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - script/build/test_db_config.sh test ci_zammad_otrs5
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb

job_integration_otrs_4:
  stage: test
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz383.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - script/build/test_db_config.sh test ci_zammad_otrs4
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb

job_integration_otrs_33:
  stage: test
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz305.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - script/build/test_db_config.sh test ci_zammad_otrs33
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb

job_integration_otrs_32:
  stage: test
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz382.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - script/build/test_db_config.sh test ci_zammad_otrs32
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb

job_integration_otrs_31:
  stage: test
  script:
    - export RAILS_ENV=test
    - export IMPORT_OTRS_ENDPOINT="http://vz381.demo.znuny.com/otrs/public.pl?Action=ZammadMigrator"
    - script/build/test_db_config.sh test ci_zammad_otrs31
    - rake db:drop;
    - rake db:create
    - rake db:migrate
    - ruby -I test/ test/integration/otrs_import_test.rb

job_integration_autowizard:
  stage: browser
  script:
    - export RAILS_ENV=production
    - export Z_LOCALES=en-us:de-de
    - export IP=$(ip -f inet -o addr show eth0|cut -d\  -f 7 | cut -d/ -f 1)
    - export BROWSER_URL=http://$IP:3011
    - export REMOTE_URL=http://192.168.122.175:4444/wd/hub
    - export BROWSER=firefox
    - export RAILS_SERVE_STATIC_FILES=true
    - script/build/test_db_config.sh production ci_zammad_autowizard
    - script/build/test_db_config.sh test ci_zammad_autowizard_test
    - RAILS_ENV=test rake db:create
    - cp contrib/auto_wizard_example.json auto_wizard.json
    - script/bootstrap.sh
    - rake assets:precompile
    - script/build/test_startup.sh $RAILS_ENV 3011
    - ruby -I test/ test/integration/auto_wizard_test.rb || script/build/test_shutdown.sh $RAILS_ENV 3011 && exit 1
    - script/build/test_shutdown.sh $RAILS_ENV 3011
