default:
  image: $CI_REGISTRY/docker/zammad-ci:3.0.4

include:
  - local: '/.gitlab/ci/base.yml'
  - local: '/.gitlab/ci/pre.yml'
  - local: '/.gitlab/ci/integration.yml'
  - local: '/.gitlab/ci/rspec.yml'
  - local: '/.gitlab/ci/vitest.yml'
  - local: '/.gitlab/ci/unit.yml'
  - local: '/.gitlab/ci/browser-core.yml'
  - local: '/.gitlab/ci/browser-integration.yml'

# Stages
stages:
  - pre
  - test
  - browser-core
  - browser-integration

# Global variables added to the ENV of each job
variables:
  # for faster translation loading
  Z_LOCALES: "en-us:de-de"
  # Browser tests and variables
  RAILS_SERVE_STATIC_FILES: "true"
  TZ: "Europe/London"
  # docker-imap-devel variables required for browser tests
  MAILNAME: "mail.test.dc.zammad.com"
  MAILBOX_INIT: "zammad@mail.test.dc.zammad.com:zammad"
  MAIL_ADDRESS: "zammad@mail.test.dc.zammad.com"
  MAIL_PASS: "zammad"
  # docker-imap-devel variables required for integration tests
  MAIL_SERVER: "mail"
  MAIL_SERVER_ACCOUNT: "zammad@mail.test.dc.zammad.com:zammad"
  MAIL_SERVER_EMAIL: "zammad@mail.test.dc.zammad.com"
  KEEP_ON_MAIL_SERVER: "mail"
  KEEP_ON_MAIL_SERVER_ACCOUNT: "zammad@mail.test.dc.zammad.com:zammad"
  # Temporary switch to enable the mobile front end for testing.
  ENABLE_EXPERIMENTAL_MOBILE_FRONTEND: 'true'

# Cache gems in between jobs and pipelines
# ATTENTION: We use a combination of the Ruby major and minor version number
# as a key for the cache to avoid cache growth and incompatibilities between
# the gems. Search hook: 3.0.4 (change it when updating the Ruby version too)
cache:
  key: "centos7ruby304"
  paths:
    - vendor/ruby
    # ATTENTION: This should be a dedicated cache only used in the job "TODO".
    # ATTENTION: Remember to update the global CI ENV setting with the latest
    #   version of the ENV from an artifact of the "TODO" job to use a valid key.
    # A dedicated cache should be used because the ENVs are not bound to the Ruby version and OS.
    # Unfortunately GitLab is not yet capable of having multiple cache-s per job
    # See: https://gitlab.com/gitlab-org/gitlab/-/issues/32814
    - fresh.env

# Initialize application env
before_script:
  - source /etc/profile.d/rvm.sh
  - echo -e "\\e[0Ksection_start:`date +%s`:bundle_install[collapsed=true]\\r\\e[0Kbundle install"
  - bundle config set --local frozen 'true'
  - bundle config set --local path 'vendor'
  - bundle install -j $(nproc)
  - echo -e "\\e[0Ksection_end:`date +%s`:bundle_install\\r\\e[0K"
  - bundle exec ruby .gitlab/configure_environment.rb
  - source .gitlab/environment.env

after_script:
  - .gitlab/environment_info.sh > log/environment_info.log