dist: trusty
sudo: false
notifications:
  email:
    - me+tv@zammad.com
env:
  - DB=mysql
  - DB=postgresql
addons:
  postgresql: "9.4"
  apt:
    packages:
      - autoconf
      - automake
      - autotools-dev
      - bison
      - build-essential
      - curl
      - git-core
      - libffi-dev
      - libgdbm-dev
      - libgmp-dev
      - libmysqlclient-dev
      - libncurses5-dev
      - libreadline6-dev
      - libsqlite3-dev
      - libssl-dev
      - libtool
      - libxml2-dev
      - libxslt1-dev
      - libyaml-0-2
      - libyaml-dev
      - mysql-client-5.6
      - mysql-client-core-5.6
      - mysql-server-5.6
      - patch
      - pkg-config
      - postfix
      - sqlite3
      - zlib1g-dev
services:
  - postgresql
  - mysql
language: ruby
rvm:
  - 2.4.4
before_install:
  - gem update
  - git fetch --unshallow
  - if [ "${DB}" = "mysql" ]; then mysql -u root -e "CREATE USER 'some_user'@'localhost' IDENTIFIED BY 'some_pass';"; fi
  - if [ "${DB}" = "mysql" ]; then mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'some_user'@'localhost';"; fi
  - if [ "${DB}" = "mysql" ]; then cp config/database.yml.test-mysql config/database.yml; fi
  - if [ "${DB}" = "postgresql" ]; then psql -c 'create database zammad_test;' -U postgres; fi
  - if [ "${DB}" = "postgresql" ]; then cp config/database.yml.test-postgresql config/database.yml; fi
  - export RAILS_ENV=test
  - export ZAMMAD_VERSION=$(git describe --tags | sed -e 's/-[a-z0-9]\{8,\}.*//g')
install:
  - if [ "${DB}" = "mysql" ]; then bundle install --without postgres; fi
  - if [ "${DB}" = "postgresql" ]; then bundle install; fi
script:
  - bundle exec rubocop
  - rake db:create
  - rake db:migrate
  - rake db:seed
  - rake test:units
  - rake test:controllers
  - ruby -I test/ test/integration/object_manager_test.rb
  - ruby -I test/ test/integration/package_test.rb
  - rake assets:precompile
  - rake db:drop
  - rake db:create
  - rake db:migrate
  - rake db:seed
  - ruby -I test/ test/integration/auto_wizard_test.rb
  - rake db:drop
  - rake db:create
  - rake db:migrate
  - rake db:seed
  - ruby -I test/ test/integration/geo_location_test.rb
  - ruby -I test/ test/integration/geo_calendar_test.rb
  - ruby -I test/ test/integration/user_agent_test.rb
  - ruby -I test/ test/integration/user_device_controller_test.rb
  - ruby -I test/ test/integration/sipgate_controller_test.rb
  - rake db:drop
after_success:
  - if [ "${DB}" = "mysql" ]; then contrib/travis-ci.org/trigger_docker_image_build.sh; fi
  - if [ "${DB}" = "mysql" ]; then contrib/travis-ci.org/trigger_docker_image_compose_build.sh; fi
  - if [ "${DB}" = "mysql" ]; then contrib/travis-ci.org/trigger_docker_image_univention_build.sh; fi
