version: '3.6'

volumes:
  visual-regression-dependencies-arm:

services:
  cypress:
    environment:
      CYPRESS_CACHE_FOLDER: $PWD/.cache/Cypress
      CYPRESS_UPDATE_SNAPSHOTS: ${CYPRESS_UPDATE_SNAPSHOTS:-true}
    platform: linux/arm64
    image: cypress/base:16.17.1
    ipc: host
    volumes:
      - ../..:/app
      - visual-regression-dependencies-arm:/app/node_modules
    working_dir: /app
    ports:
      - "8000:8000"
      - "443:443"
    command: bash ./.cypress/visual-regression/run.sh
