---
# % character in the URL has to be escaped (% => %%)
url: "https://www.google.com/calendar/ical/%{domain}%%23holiday%%40group.v.calendar.google.com/public/basic.ics"

# Mapping from country to domain
countries:
  Australia: en.australian
  Austria: de.austrian
  Argentina: en.ar
  Bahamas: en.bs
  Belarus: en.by
  Brazil: en.brazilian
  Bulgaria: en.bulgarian
  Canada: en.canadian
  China: en.china
  Chile: en.cl
  Costa Rica: en.cr
  Colombia: en.co
  Croatia: en.croatian
  Cuba: en.cu
  Cyprus: de.cy
  Switzerland: de.ch
  Denmark: da.danish
  Netherlands: nl.dutch
  Egypt: en.eg
  Ethiopia: en.et
  Ecuador: en.ec
  Estonia: en.ee
  Finland: en.finnish
  France: en.french
  Germany: de.german
  Greece: en.greek
  Ghana: en.gh
  Hong Kong: en.hong_kong
  Haiti: en.ht
  Hungary: en.hungarian
  India: en.indian
  Indonesia: en.indonesian
  Iran: en.ir
  Ireland: en.irish
  Italy: it.italian
  Israel: en.jewish
  Japan: en.japanese
  Kuwait: en.kw
  Latvia: en.latvian
  Liechtenstein: en.li
  Lithuania: en.lithuanian
  Luxembourg: en.lu
  Malaysia: en.malaysia
  Mexico: en.mexican
  Morocco: en.ma
  Mauritius: en.mu
  Moldova: en.md
  New Zealand: en.new_zealand
  Norway: en.norwegian
  Philippines: en.philippines
  Poland: en.polish
  Portugal: en.portuguese
  Pakistan: en.pk
  Russia: en.russian
  Senegal: en.sn
  Singapore: en.singapore
  South Africa: en.sa
  South Korean: en.south_korea
  Spain: en.spain
  Slovakia: en.slovak
  Serbia: en.rs
  Slovenia: en.slovenian
  Sweden: en.swedish
  Taiwan: en.taiwan
  Thai: en.th
  Turkey: en.turkish
  UK: en.uk
  US: en.usa
  Ukraine: en.ukrainian
  Uruguay: en.uy
  Vietnam: en.vietnamese
  Venezuela: en.ve
