.variables_selenium_firefox:
  variables:
    REMOTE_URL: 'http://selenium-firefox:4444/wd/hub'
    BROWSER: 'firefox'
    BROWSER_HEADLESS: 'true'
    START_XVFB: 'false' # not needed for headless mode
    SE_NODE_MAX_SESSIONS: '5'
    SE_NODE_OVERRIDE_MAX_SESSIONS: 'true'
    SE_OPTS: '--log /builds/selenium.log'

.variables_selenium_chrome:
  variables:
    REMOTE_URL: 'http://selenium-chrome:4444/wd/hub'
    BROWSER: chrome
    BROWSER_HEADLESS: 'true'
    START_XVFB: 'false' # not needed for headless mode
    SE_NODE_MAX_SESSIONS: '5'
    SE_NODE_OVERRIDE_MAX_SESSIONS: 'true'
    SE_OPTS: '--log /builds/selenium.log'
    CHROME_LOG_FILE: '/builds/chrome.log'

.variables_proxy:
  variables:
    CI_PROXY_URL: 'ci-service-proxy:3128'
    CI_PROXY_USER: 'zammad'
    CI_PROXY_PASSWORD: 'zammad'

.variables_mattermost:
  variables:
    MATTERMOST_URL: 'http://ci-service-mattermost:8065'
    MATTERMOST_USER: 'zammad'
    MATTERMOST_PASSWORD: 'ZammaD-2024-Mattermost!'
    MATTERMOST_CHANNEL: 'zammad-channel'

.variables_idoit:
  variables:
    IDOIT_API_CATEGORY: 'Building'
    IDOIT_API_ENDPOINT: 'http://ci-service-idoit:80'
    IDOIT_API_TOKEN: 'admin'

.variables_ftp:
  variables:
    FTP_URL: 'ftp://ci-service-ftp'

.variables_auth:
  variables:
    KEYCLOAK_BASE_URL: 'http://ci-service-auth:8080'
    KEYCLOAK_CREATE_ADMIN_USER: 'true'
    KEYCLOAK_ADMIN_USER: 'admin'
    KEYCLOAK_ADMIN_PASSWORD: 'admin'
    KEYCLOAK_DATABASE_VENDOR: 'dev-file'
    KEYCLOAK_EXTRA_ARGS: '--import-realm'

.variables_s3:
  variables:
    S3_URL: http://zammadadmin:zammadadmin@ci-service-s3:9000/zammad?region=de-zammad-s1&force_path_style=true
    MINIO_ROOT_USER: zammadadmin
    MINIO_ROOT_PASSWORD: zammadadmin
    MINIO_DEFAULT_BUCKET: zammad

.services:
  mysql:
    name: $CI_REGISTRY/docker/zammad-mysql:stable
    alias: mysql

  mariadb:
    name: $CI_REGISTRY/docker/zammad-mariadb:stable
    alias: mysql

  postgresql:
    name: $CI_REGISTRY/docker/zammad-postgresql:$POSTGRESQL_TAG
    alias: postgresql

  elasticsearch:
    name: $CI_REGISTRY/docker/zammad-elasticsearch:$ELASTICSEARCH_TAG
    alias: elasticsearch

  selenium-chrome:
    name: $CI_REGISTRY/docker/zammad-selenium-chrome:stable
    alias: selenium-chrome

  selenium-firefox:
    name: $CI_REGISTRY/docker/zammad-selenium-firefox:stable
    alias: selenium-firefox

  redis:
    name: $CI_REGISTRY/docker/zammad-redis:$REDIS_TAG
    alias: redis

  memcached:
    name: $CI_REGISTRY/docker/zammad-memcached:stable
    alias: memcached
    command: ['memcached', '-m', '256M']

  imap:
    name: $CI_REGISTRY/docker/zammad-imap:stable
    alias: mail

  proxy:
    name: $CI_REGISTRY/docker/zammad-proxies:stable
    alias: ci-service-proxy

  auth:
    name: $CI_REGISTRY/docker/zammad-auth:stable
    alias: ci-service-auth

  mattermost:
    name: $CI_REGISTRY/docker/zammad-mattermost:stable
    alias: ci-service-mattermost

  idoit:
    name: $CI_REGISTRY/docker/zammad-idoit:stable
    alias: ci-service-idoit

  ftp:
    name: $CI_REGISTRY/docker/zammad-ftp:stable
    alias: ci-service-ftp

  ldap:
    name: $CI_REGISTRY/docker/zammad-ldap:stable
    alias: ci-service-ldap

  s3:
    name: $CI_REGISTRY/docker/zammad-s3:stable
    alias: ci-service-s3
    command: ['server', '/data']
