name: build-docker-compose-images

on:
  push:
    branches: [stable**]

jobs:
  build-docker-compose-images:
    runs-on: ubuntu-latest
    env:
      DOCKER_GITHUB_REPOSITORY: "zammad-docker-compose"
      DOCKER_IMAGES: "zammad zammad-elasticsearch zammad-postgresql"
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REPOSITORY: "zammad-docker-compose"
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    steps:
     - name: Alias GITHUB_ACTOR as REPO_USER
      run: |
        echo "::set-env name=REPO_USER::$GITHUB_ACTOR"
     - name: Checkout code
        uses: actions/checkout@master
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
      - name: Build docker image
        run: .github/docker-image-build.sh
